const STORAGE_KEY = 'vb_config_v1';

// Repair projects saved with the old buggy subtree prefix
// (e.g. "projects/rbb" or "projects/kamana-sewa-b") → use the shared base prefix
function migrateProjects(parsed) {
  const defaultPrefix = parsed.defaultSubtreePath || 'projects/base-client';
  const defaultBasePath = parsed.defaultSubtreeBasePath || 'fonebank/banksmart-client-web';

  parsed.defaultSubtreePath = defaultPrefix;
  if (!parsed.defaultSubtreeBasePath || parsed.defaultSubtreeBasePath === 'fonebank/banksmart-cli') {
    parsed.defaultSubtreeBasePath = defaultBasePath;
  }

  parsed.projects = (parsed.projects || []).map((p) => {
    if (p.type === 'subtree') {
      const lastSegment = (p.path || '').split('/').pop() || '';
      const isOldAutoGenerated =
        !p.subtreePath ||
        p.subtreePath === `projects/${lastSegment}` ||
        p.subtreePath.startsWith(`projects/${lastSegment.slice(0, 10)}`) ||
        (p.subtreePath.startsWith('projects/') && p.subtreePath !== defaultPrefix && p.subtreePath !== 'projects/base-client');

      const isOldCliBase =
        !p.basePath ||
        p.basePath === 'fonebank/banksmart-cli' ||
        p.basePath.endsWith('/banksmart-cli');

      return {
        ...p,
        subtreePath: isOldAutoGenerated ? defaultPrefix : p.subtreePath,
        basePath: isOldCliBase ? defaultBasePath : p.basePath,
      };
    }
    return p;
  });
  return parsed;
}

export function loadConfig() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!parsed.rememberToken) parsed.token = '';
    return migrateProjects(parsed);
  } catch (e) {
    console.warn('Failed to load config', e);
    return null;
  }
}

export function saveConfig(state) {
  const toStore = { ...state };
  if (!state.rememberToken) toStore.token = '';
  localStorage.setItem(STORAGE_KEY, JSON.stringify(toStore));
}